package main.specifications;

public enum sym {



    TRUE, FALSE, VAR, POW, OPEN_CURLY_BRACKET, CLOSE_CURLY_BRACKET,
            OPEN_PARENTHESES,    CLOSE_PARENTHESES, OPEN_SQUARE_BRACKET, CLOSE_SQUARE_BRACKET,
            LESS_THAN,    GREATER_THAN, ASSIGN,    PLUS,
            MINUS, TIMES, EQUAL,    NOT_EQUAL, LESS_THAN_OR_EQUAL, GREATER_THAN_OR_EQUAL,
            AND, OR, XOR, NOT, IMPORT,     FROM, IF, ELSE, RETURN , REPEAT, PRINT,  WHILE, RENDER, COMPONENT,
            IDENTIFIER, INTEGER, DOUBLE, PANEL, TEXT, TEXTFIELD, BUTTON, LIST, ELEMENTS, ITEM, DEFAULT, SPINNER, MAX, MIN, IMAGE, ID, X, Y,
            HEIGHT, WIDTH, COLOR, BORDER, CLASS_NAME, SLASH,STRING_LITERAL, SEMI, COMA, DIV, ERROR




}
